### ISSUE TITLE
Crash on Intel using AVX

### ISSUE THREAD

**Issue by RandssINC** [JohnnyFFM/blagominer#1] opened 2018-06-09 12:59 UTC
This only happens with the Intel AVX systems I have.  AMD FX/APU AVX are fine.  Intel SSE works.

Faulting application name: BlagoMiner_avx.exe, version: 0.0.0.0, time stamp: 0x5b1bafc3
Faulting module name: BlagoMiner_avx.exe, version: 0.0.0.0, time stamp: 0x5b1bafc3
Exception code: 0xc000001d
Fault offset: 0x000000000001b4d4
Faulting process id: 0xa44
Faulting application start time: 0x01d3ffeef044d979
Faulting application path: C:\Users\Owner\Desktop\newest\BlagoMiner_avx.exe
Faulting module path: C:\Users\Owner\Desktop\newest\BlagoMiner_avx.exe

Happens right at startup of miner.  Currently using 911b7-AVX on these systems with no error.
Cheers!

**Comment by RandssINC** [comment] 2018-06-09 16:05
Just ran this build on a AMD FX 4100 nad it also crashed.  Also noticed that two events where logged.  Here is the other one.

Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program BlagoMiner_avx.exe because of this error.

Program: BlagoMiner_avx.exe
File: 

The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
	- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
	- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.

Additional Data
Error value: 3FA3B4D4

**Comment by gsxryan** [comment] 2018-06-10 19:40
I can confirm successful use on an AVX I7 3770.  Cannot reproduce.

**Comment by JohnnyFFM** [comment] 2018-06-10 20:05
Seems like the issue has been resolved. Closing this now. Thanks for testing!

**Closed** 2018-06-10 20:05 UTC
